{% set name = "human-learn" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/human-learn-{{ version }}.tar.gz
  sha256: f9f89479038d055d5fb6b5d06556968b2ff579ac7079895fba4735b29a31500c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bokeh <3.0.0,>=2.2.1
    - clumper >=0.2.5
    - pandas >=0.23.4
    - python >=3.6
    - scikit-learn >=0.23.2
    - shapely >=1.7.1

test:
  imports:
    - hulearn
    - hulearn.classification
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/human-learn/
  summary: natural intelligence benchmarks for scikit-learn
  dev_url: https://github.com/koaning/human-learn
  doc_url: https://koaning.github.io/human-learn/
  description: |
    Contains scikit-learn compatible tools that should make it easier to construct 
    and benchmark rule based systems that are designed by humans.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
